name: Python CI/CD for Fraud Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use a Linux environment for consistency

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Specify a stable Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install project dependencies from requirements.txt
        pip install -r requirements.txt
        # nbconvert is needed to execute notebooks

    - name: Create data directory and copy placeholder data
     
      # For CI, we'll create dummy files to ensure the notebooks can load them
      # without failing due to missing files.
      run: |
        mkdir -p data
        # Create dummy CSV files if they don't exist, so notebooks can load them
        echo "user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,ip_address,class" > data/Fraud_Data.csv
        echo "1,2023-01-01 00:00:00,2023-01-01 00:01:00,100,device1,Direct,Chrome,M,25,123456789,0" >> data/Fraud_Data.csv
        echo "2,2023-01-01 00:02:00,2023-01-01 00:03:00,200,device2,Ads,Firefox,F,30,987654321,1" >> data/Fraud_Data.csv

        echo "lower_bound_ip_address,upper_bound_ip_address,country" > data/IpAddress_to_Country.csv
        echo "0,999999999,CountryA" >> data/IpAddress_to_Country.csv
        echo "1000000000,4294967295,CountryB" >> data/IpAddress_to_Country.csv

        echo "Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class" > data/creditcard.csv
        echo "0.0,-0.1,-0.2,-0.3,-0.4,-0.5,-0.6,-0.7,-0.8,-0.9,-1.0,-1.1,-1.2,-1.3,-1.4,-1.5,-1.6,-1.7,-1.8,-1.9,-2.0,-2.1,-2.2,-2.3,-2.4,-2.5,-2.6,-2.7,-2.8,10.0,0" >> data/creditcard.csv
        echo "1.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,20.0,1" >> data/creditcard.csv

    - name: Add src to Python Path
      # This ensures Python can find your modules when running tests and notebooks
      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

    - name: Run Unit Tests
      run: |
        pytest tests/

    - name: Execute eda.ipynb
      run: |
        jupyter nbconvert --to notebook --execute notebooks/eda.ipynb --output eda_executed.ipynb
      # This runs the notebook and saves the output. If it errors, the step fails.

    - name: Execute modeling.ipynb
      run: |
        jupyter nbconvert --to notebook --execute notebooks/modeling.ipynb --output modeling_executed.ipynb

    - name: Execute explainability.ipynb
      run: |
        jupyter nbconvert --to notebook --execute notebooks/explainability.ipynb --output explainability_executed.ipynb

    - name: Upload executed notebooks (optional, for debugging)
      uses: actions/upload-artifact@v4
      with:
        name: executed-notebooks
        path: |
          eda_executed.ipynb
          modeling_executed.ipynb
          explainability_executed.ipynb
      if: always()
